name: Unity WebGL Build and Linting

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - uses: actions/cache@v3
        with:
          path: "Unity Project/Dungeoneering/Library"
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Test
    #   - name: Run tests
    #     uses: game-ci/unity-test-runner@v4
    #     env:
    #       UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    #       UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    #       UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    #     with:
    #       githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      # - name: Build project
      #   uses: game-ci/unity-builder@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     projectPath: "Unity Project/Dungeoneering"
      #     buildName: WebGLBuild
      #     targetPlatform: WebGL

    # Ideally we would lint before building but build generates csproj files which allow linting
      - name: ls
        working-directory: "Unity Project/Dungeoneering"
        run: echo "$(pwd) $(ls)"
      - name: dotnet format check
        working-directory: "Unity Project/Dungeoneering"
        run: dotnet format style --verify-no-changes --verbosity diagnostic CaptainCoder.Unity.csproj

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build